# Generated by Django 5.1.3 on 2024-12-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=50, unique=True)),
                ('id_tanque', models.CharField(max_length=50, unique=True)),
                ('quantidade_povoada', models.PositiveIntegerField()),
                ('data_povoamento', models.DateField()),
                ('data_retirada', models.DateField()),
                ('quantidade_retirada', models.PositiveIntegerField()),
            ],
        ),
    ]
