# Generated by Django 5.1.4 on 2024-12-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0003_remove_tanque_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanque',
            name='quantidade_retirada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
