# Generated by Django 5.1.4 on 2025-02-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0005_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tanque',
            name='previsao_retirada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nome_produto',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
