# Generated by Django 5.1.4 on 2025-02-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0008_remove_tanque_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
