# Generated by Django 5.1.4 on 2025-02-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0009_tanque_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tanque',
            old_name='estado',
            new_name='estado_ativo',
        ),
    ]
