# Generated by Django 5.1.4 on 2025-02-12 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0010_rename_estado_tanque_estado_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='quantidade_atual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HistoricoDespovoamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_retirada', models.PositiveIntegerField()),
                ('data_retirada', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='gerenciamento.tanque')),
            ],
        ),
    ]
