# Generated by Django 5.1.4 on 2025-02-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0014_retiradaparcial_delete_historicotanque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retiradaparcial',
            old_name='data',
            new_name='data_retirada',
        ),
        migrations.RenameField(
            model_name='retiradaparcial',
            old_name='quantidade',
            new_name='quantidade_retirada',
        ),
        migrations.RemoveField(
            model_name='retiradaparcial',
            name='finalizada',
        ),
    ]
