# Generated by Django 5.1.4 on 2025-02-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0015_rename_data_retiradaparcial_data_retirada_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetiradaParcial',
        ),
    ]
