# Generated by Django 5.1.4 on 2025-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0017_retiradaparcial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiradaparcial',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retiradaparcial',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
