# Generated by Django 5.1.4 on 2025-02-19 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0018_alter_retiradaparcial_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
                ('quantidade_povoada', models.PositiveIntegerField()),
                ('data_povoamento', models.DateField()),
                ('previsao_retirada', models.DateField(blank=True, null=True)),
                ('data_real_retirada', models.DateField()),
                ('taxa_sobrevivencia', models.FloatField()),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_baixas', to='gerenciamento.tanque')),
            ],
        ),
    ]
