# Generated by Django 5.1.4 on 2025-02-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0020_notificacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
